const constants = {
  FETCH_CATEGOTIES: 'FETCH_CATEGOTIES',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_PRODUCTS: 'SET_PRODUCTS',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CHANGE_AMOUNT: 'CHANGE_AMOUNT',
  LOADING_PRODUCTS: 'LOADING_PRODUCTS',
  LOADING_CATEGORIES: 'LOADING_CATEGORIES',
  API_START: 'API_START',
  API_END: 'API_END',
  API: 'API'
};

export default constants;
